drop extension if exists "pg_net";


  create table "public"."grocery_aisles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "display_order" bigint not null
      );


alter table "public"."grocery_aisles" enable row level security;


  create table "public"."grocery_list_items" (
    "id" uuid not null default gen_random_uuid(),
    "grocery_list_id" uuid,
    "ingredient_id" bigint,
    "quantity" numeric,
    "unit_id" uuid,
    "notes" text,
    "is_checked" boolean default false,
    "is_manual" boolean default false,
    "source_recipes" uuid[],
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "manual_name" text
      );


alter table "public"."grocery_list_items" enable row level security;


  create table "public"."grocery_list_recipes" (
    "id" uuid not null default gen_random_uuid(),
    "grocery_list_id" uuid,
    "servings_multiplier" numeric default 1.0,
    "added_at" timestamp without time zone default now(),
    "recipe_id" uuid
      );


alter table "public"."grocery_list_recipes" enable row level security;


  create table "public"."grocery_lists" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null default auth.uid(),
    "name" text not null,
    "description" text,
    "updated_at" timestamp without time zone default now(),
    "is_completed" boolean not null default false
      );


alter table "public"."grocery_lists" enable row level security;


  create table "public"."ingredients" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "grocery_aisle_id" bigint,
    "subaisle_position_id" bigint
      );


alter table "public"."ingredients" enable row level security;


  create table "public"."recipe_ingredients" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "ingredient_id" bigint not null,
    "note" text default ''::text,
    "unit_id" uuid not null default 'f97badf3-daeb-4f07-84df-9bd19e7726e8'::uuid,
    "unit_amount" numeric default '1'::numeric,
    "recipe_id" uuid
      );


alter table "public"."recipe_ingredients" enable row level security;


  create table "public"."recipes" (
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "image_url" text,
    "steps" text[] not null,
    "created_by" uuid not null default auth.uid(),
    "servings" bigint not null,
    "id" uuid not null default gen_random_uuid()
      );


alter table "public"."recipes" enable row level security;


  create table "public"."subaisle_positions" (
    "id" bigint generated always as identity not null,
    "grocery_aisle_id" bigint not null,
    "name" text not null,
    "position" bigint not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."subaisle_positions" enable row level security;


  create table "public"."units" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "abbreviation" text not null default ''::text,
    "type" text not null,
    "system" text not null,
    "base_conversion_factor" numeric,
    "created_at" timestamp without time zone default now()
      );


alter table "public"."units" enable row level security;


  create table "public"."units_backup_before_fix" (
    "id" uuid,
    "name" text,
    "abbreviation" text,
    "type" text,
    "system" text,
    "base_conversion_factor" numeric,
    "display_order" integer,
    "created_at" timestamp without time zone
      );


alter table "public"."units_backup_before_fix" enable row level security;

CREATE UNIQUE INDEX grocery_aisle_display_order_key ON public.grocery_aisles USING btree (display_order);

CREATE UNIQUE INDEX grocery_aisle_name_key ON public.grocery_aisles USING btree (name);

CREATE UNIQUE INDEX grocery_aisle_pkey ON public.grocery_aisles USING btree (id);

CREATE UNIQUE INDEX grocery_list_items_pkey ON public.grocery_list_items USING btree (id);

CREATE UNIQUE INDEX grocery_list_recipes_grocery_list_id_recipe_id_key ON public.grocery_list_recipes USING btree (grocery_list_id, recipe_id);

CREATE UNIQUE INDEX grocery_list_recipes_pkey ON public.grocery_list_recipes USING btree (id);

CREATE UNIQUE INDEX grocery_lists_pkey ON public.grocery_lists USING btree (id);

CREATE INDEX idx_grocery_list_items_checked ON public.grocery_list_items USING btree (grocery_list_id, is_checked);

CREATE INDEX idx_grocery_list_items_ingredient ON public.grocery_list_items USING btree (ingredient_id);

CREATE INDEX idx_grocery_list_items_ingredient_id ON public.grocery_list_items USING btree (ingredient_id);

CREATE INDEX idx_grocery_list_items_list_id ON public.grocery_list_items USING btree (grocery_list_id);

CREATE INDEX idx_grocery_list_items_unit_id ON public.grocery_list_items USING btree (unit_id);

CREATE INDEX idx_grocery_list_recipes_list_id ON public.grocery_list_recipes USING btree (grocery_list_id);

CREATE INDEX idx_grocery_lists_user_id ON public.grocery_lists USING btree (user_id);

CREATE INDEX idx_recipe_ingredients_unit_lookup ON public.recipe_ingredients USING btree (ingredient_id, unit_id) WHERE (unit_amount IS NOT NULL);

CREATE UNIQUE INDEX ingredient_name_key ON public.ingredients USING btree (name);

CREATE UNIQUE INDEX ingredient_pkey ON public.ingredients USING btree (id);

CREATE UNIQUE INDEX recipe_ingredients_pkey ON public.recipe_ingredients USING btree (id);

CREATE UNIQUE INDEX recipes_pkey ON public.recipes USING btree (id);

CREATE UNIQUE INDEX subaisle_positions_grocery_aisle_id_position_key ON public.subaisle_positions USING btree (grocery_aisle_id, "position");

CREATE UNIQUE INDEX subaisle_positions_pkey ON public.subaisle_positions USING btree (id);

CREATE UNIQUE INDEX units_name_key ON public.units USING btree (name);

CREATE UNIQUE INDEX units_pkey ON public.units USING btree (id);

alter table "public"."grocery_aisles" add constraint "grocery_aisle_pkey" PRIMARY KEY using index "grocery_aisle_pkey";

alter table "public"."grocery_list_items" add constraint "grocery_list_items_pkey" PRIMARY KEY using index "grocery_list_items_pkey";

alter table "public"."grocery_list_recipes" add constraint "grocery_list_recipes_pkey" PRIMARY KEY using index "grocery_list_recipes_pkey";

alter table "public"."grocery_lists" add constraint "grocery_lists_pkey" PRIMARY KEY using index "grocery_lists_pkey";

alter table "public"."ingredients" add constraint "ingredient_pkey" PRIMARY KEY using index "ingredient_pkey";

alter table "public"."recipe_ingredients" add constraint "recipe_ingredients_pkey" PRIMARY KEY using index "recipe_ingredients_pkey";

alter table "public"."recipes" add constraint "recipes_pkey" PRIMARY KEY using index "recipes_pkey";

alter table "public"."subaisle_positions" add constraint "subaisle_positions_pkey" PRIMARY KEY using index "subaisle_positions_pkey";

alter table "public"."units" add constraint "units_pkey" PRIMARY KEY using index "units_pkey";

alter table "public"."grocery_aisles" add constraint "grocery_aisle_display_order_key" UNIQUE using index "grocery_aisle_display_order_key";

alter table "public"."grocery_aisles" add constraint "grocery_aisle_name_key" UNIQUE using index "grocery_aisle_name_key";

alter table "public"."grocery_list_items" add constraint "grocery_list_items_grocery_list_id_fkey" FOREIGN KEY (grocery_list_id) REFERENCES public.grocery_lists(id) ON DELETE CASCADE not valid;

alter table "public"."grocery_list_items" validate constraint "grocery_list_items_grocery_list_id_fkey";

alter table "public"."grocery_list_items" add constraint "grocery_list_items_ingredient_id_fkey" FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id) ON DELETE SET NULL not valid;

alter table "public"."grocery_list_items" validate constraint "grocery_list_items_ingredient_id_fkey";

alter table "public"."grocery_list_items" add constraint "grocery_list_items_unit_id_fkey" FOREIGN KEY (unit_id) REFERENCES public.units(id) ON DELETE SET NULL not valid;

alter table "public"."grocery_list_items" validate constraint "grocery_list_items_unit_id_fkey";

alter table "public"."grocery_list_items" add constraint "manual_name_check" CHECK ((((is_manual = true) AND (((manual_name IS NOT NULL) AND (length(TRIM(BOTH FROM manual_name)) > 0)) OR ((manual_name IS NULL) AND (ingredient_id IS NOT NULL)))) OR ((is_manual = false) AND (manual_name IS NULL) AND (ingredient_id IS NOT NULL)))) not valid;

alter table "public"."grocery_list_items" validate constraint "manual_name_check";

alter table "public"."grocery_list_recipes" add constraint "grocery_list_recipes_grocery_list_id_fkey" FOREIGN KEY (grocery_list_id) REFERENCES public.grocery_lists(id) ON DELETE CASCADE not valid;

alter table "public"."grocery_list_recipes" validate constraint "grocery_list_recipes_grocery_list_id_fkey";

alter table "public"."grocery_list_recipes" add constraint "grocery_list_recipes_grocery_list_id_recipe_id_key" UNIQUE using index "grocery_list_recipes_grocery_list_id_recipe_id_key";

alter table "public"."grocery_list_recipes" add constraint "grocery_list_recipes_recipe_id_fkey" FOREIGN KEY (recipe_id) REFERENCES public.recipes(id) ON DELETE CASCADE not valid;

alter table "public"."grocery_list_recipes" validate constraint "grocery_list_recipes_recipe_id_fkey";

alter table "public"."grocery_lists" add constraint "grocery_lists_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."grocery_lists" validate constraint "grocery_lists_user_id_fkey";

alter table "public"."ingredients" add constraint "ingredient_name_key" UNIQUE using index "ingredient_name_key";

alter table "public"."ingredients" add constraint "ingredients_grocery_aisle_id_fkey" FOREIGN KEY (grocery_aisle_id) REFERENCES public.grocery_aisles(id) ON UPDATE CASCADE ON DELETE SET DEFAULT not valid;

alter table "public"."ingredients" validate constraint "ingredients_grocery_aisle_id_fkey";

alter table "public"."ingredients" add constraint "ingredients_subaisle_position_id_fkey" FOREIGN KEY (subaisle_position_id) REFERENCES public.subaisle_positions(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."ingredients" validate constraint "ingredients_subaisle_position_id_fkey";

alter table "public"."recipe_ingredients" add constraint "recipe_ingredients_ingredient_id_fkey" FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id) ON DELETE SET NULL not valid;

alter table "public"."recipe_ingredients" validate constraint "recipe_ingredients_ingredient_id_fkey";

alter table "public"."recipe_ingredients" add constraint "recipe_ingredients_recipe_id_fkey" FOREIGN KEY (recipe_id) REFERENCES public.recipes(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."recipe_ingredients" validate constraint "recipe_ingredients_recipe_id_fkey";

alter table "public"."recipe_ingredients" add constraint "recipe_ingredients_unit_id_fkey" FOREIGN KEY (unit_id) REFERENCES public.units(id) not valid;

alter table "public"."recipe_ingredients" validate constraint "recipe_ingredients_unit_id_fkey";

alter table "public"."recipes" add constraint "recipes_name_check" CHECK ((length(name) < 100)) not valid;

alter table "public"."recipes" validate constraint "recipes_name_check";

alter table "public"."recipes" add constraint "recipes_servings_check" CHECK (((servings < 300) AND (servings > 0))) not valid;

alter table "public"."recipes" validate constraint "recipes_servings_check";

alter table "public"."subaisle_positions" add constraint "subaisle_positions_grocery_aisle_id_fkey" FOREIGN KEY (grocery_aisle_id) REFERENCES public.grocery_aisles(id) ON DELETE CASCADE not valid;

alter table "public"."subaisle_positions" validate constraint "subaisle_positions_grocery_aisle_id_fkey";

alter table "public"."subaisle_positions" add constraint "subaisle_positions_grocery_aisle_id_position_key" UNIQUE using index "subaisle_positions_grocery_aisle_id_position_key";

alter table "public"."units" add constraint "units_base_conversion_factor_check" CHECK ((base_conversion_factor > (0)::numeric)) not valid;

alter table "public"."units" validate constraint "units_base_conversion_factor_check";

alter table "public"."units" add constraint "units_name_key" UNIQUE using index "units_name_key";

alter table "public"."units" add constraint "units_system_check" CHECK ((system = ANY (ARRAY['imperial'::text, 'metric'::text, 'universal'::text]))) not valid;

alter table "public"."units" validate constraint "units_system_check";

alter table "public"."units" add constraint "units_type_check" CHECK ((type = ANY (ARRAY['volume'::text, 'count'::text, 'weight'::text]))) not valid;

alter table "public"."units" validate constraint "units_type_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.add_manual_item_to_grocery_list(list_id uuid, ingredient_name text, quantity numeric, unit_name text, notes text DEFAULT NULL::text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$DECLARE
  ingredient_id bigint;
  manual_name text;
  unit_id uuid;
  item_id uuid;
BEGIN
  -- Find or create ingredient
  SELECT id INTO ingredient_id FROM ingredients WHERE name ILIKE ingredient_name;
  IF NOT FOUND THEN
    manual_name = ingredient_name;
  END IF;
  
  -- Find unit
  SELECT id INTO unit_id FROM units WHERE name = unit_name;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Unit "%" not found', unit_name;
  END IF;
  
  -- Insert manual item
  INSERT INTO grocery_list_items (
    grocery_list_id,
    ingredient_id,
    quantity,
    unit_id,
    notes,
    is_manual,
    manual_name,
    source_recipes
  ) VALUES (
    list_id,
    ingredient_id,
    quantity,
    unit_id,
    notes,
    true,
    manual_name,
    '{}'
  ) RETURNING id INTO item_id;
  
  RETURN item_id;
END;$function$
;

CREATE OR REPLACE FUNCTION public.add_recipe_to_grocery_list(list_id uuid, p_recipe_id uuid, servings_multiplier numeric DEFAULT 1.0)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$ 
BEGIN 
    INSERT INTO public.grocery_list_recipes (grocery_list_id, recipe_id, servings_multiplier) 
    VALUES (list_id, p_recipe_id, servings_multiplier) 
    ON CONFLICT (grocery_list_id, recipe_id) 
    DO UPDATE SET servings_multiplier = EXCLUDED.servings_multiplier; 
    
    RETURN true; 
END; 
$function$
;

CREATE OR REPLACE FUNCTION public.delete_old_anonymous_users()
 RETURNS TABLE(deleted_count integer)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$DECLARE
    total_deleted INTEGER;
BEGIN
    -- Delete anonymous users older than 24 hours from auth.users
    WITH deleted_users AS (
        DELETE FROM auth.users
        WHERE 
            -- Check if the user is anonymous (no email)
            email IS NULL 
            -- Check if the user is older than 24 hours
            AND created_at < NOW() - INTERVAL '24 hours'
        RETURNING id
    )
    SELECT COUNT(*) INTO total_deleted FROM deleted_users;

    RETURN QUERY SELECT total_deleted;
END;$function$
;

CREATE OR REPLACE FUNCTION public.find_best_unit_for_quantity(p_base_quantity numeric, p_unit_type text, p_preferred_system text DEFAULT 'imperial'::text)
 RETURNS uuid
 LANGUAGE plpgsql
AS $function$
DECLARE
  best_unit_id uuid;
BEGIN
  -- Select unit that results in the most readable quantity (between 0.25 and 999)
  SELECT id INTO best_unit_id
  FROM (
    SELECT 
      u.id,
      ABS(LOG(p_base_quantity / NULLIF(u.base_conversion_factor, 0))) as log_distance,
      p_base_quantity / NULLIF(u.base_conversion_factor, 1) as converted_qty
    FROM units u
    WHERE u.type = p_unit_type
      AND u.base_conversion_factor IS NOT NULL
      AND u.system = p_preferred_system
      AND p_base_quantity / NULLIF(u.base_conversion_factor, 1) BETWEEN 0.25 AND 999
    ORDER BY log_distance ASC
    LIMIT 1
  ) suitable_units;
  
  -- Fallback to any unit of the correct type if no suitable unit found
  IF best_unit_id IS NULL THEN
    SELECT id INTO best_unit_id
    FROM units
    WHERE type = p_unit_type
      AND system = p_preferred_system
    ORDER BY display_order ASC
    LIMIT 1;
  END IF;
  
  RETURN best_unit_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.generate_simple_anonymous_username()
 RETURNS text
 LANGUAGE plpgsql
AS $function$DECLARE
    username text;
BEGIN
    username := 'anon_' || lower(replace(gen_random_uuid()::text, '-', ''));
    RETURN username;
END;$function$
;

CREATE OR REPLACE FUNCTION public.get_public_and_user_recipes()
 RETURNS TABLE(id uuid, name text, image_url text, created_by uuid, steps text[], servings bigint, created_at timestamp with time zone)
 LANGUAGE sql
 SECURITY DEFINER
AS $function$ 
SELECT id, name, image_url, created_by, steps, servings, created_at
FROM recipes
WHERE created_by = '6e0258f5-c980-47d2-a7ee-981e76e56333'
OR created_by = auth.uid();
$function$
;

CREATE OR REPLACE FUNCTION public.get_public_recipes()
 RETURNS TABLE(id uuid, name text, image_url text, created_by uuid, steps text[], servings bigint, created_at timestamp with time zone)
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
    SELECT id, name, image_url, created_by, steps, servings, created_at 
    FROM recipes
    WHERE created_by = '6e0258f5-c980-47d2-a7ee-981e76e56333';
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_anonymous_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$DECLARE
    generated_display_name text;
BEGIN
    -- Only proceed if the provider type is 'Anonymous'
    IF NEW.raw_app_meta_data->>'Provider type' = 'Anonymous' THEN
        -- Generate a unique display name
        generated_display_name := 'anon_' || lower(replace(gen_random_uuid()::text, '-', ''));
        
        -- Ensure user_metadata exists and is a valid JSONB
        IF NEW.user_metadata IS NULL THEN
            NEW.user_metadata := '{}'::jsonb;
        END IF;
        
        -- Set the display name in user_metadata
        NEW.user_metadata := NEW.user_metadata || 
            jsonb_build_object('displayName', generated_display_name);
    END IF;
    
    RETURN NEW;
END;$function$
;

CREATE OR REPLACE FUNCTION public.regenerate_grocery_list_items(list_id uuid)
 RETURNS void
 LANGUAGE plpgsql
AS $function$DECLARE
  recipe_record RECORD;
  ingredient_record RECORD;
  existing_item RECORD;
  total_base_quantity decimal;
  preferred_unit_id uuid;
  converted_quantity decimal;
BEGIN
  -- Delete all non-manual items first
  DELETE FROM grocery_list_items 
  WHERE grocery_list_id = list_id AND is_manual = false;
  
  -- Create temp table to collect ingredients without base conversion
  -- This will allow us to handle units without conversion separately
  CREATE TEMP TABLE temp_ingredient_no_conversion (
    ingredient_id bigint,
    unit_id uuid,
    total_quantity decimal,
    unit_type text,
    source_recipes uuid[],
    notes text,
    has_null_quantity boolean DEFAULT false,
    PRIMARY KEY (ingredient_id, unit_id)
  ) ON COMMIT DROP;
  
  -- Create temp table to collect all ingredient quantities in base units
  CREATE TEMP TABLE temp_ingredient_aggregation (
    ingredient_id bigint,
    total_base_quantity decimal,
    unit_type text,
    source_recipes uuid[],
    notes text,
    has_null_quantity boolean DEFAULT false,
    PRIMARY KEY (ingredient_id, unit_type)
  ) ON COMMIT DROP;
  
  -- Create temp table for ingredients with null quantities
  CREATE TEMP TABLE temp_null_quantity_ingredients (
    ingredient_id bigint,
    unit_id uuid,
    source_recipes uuid[],
    notes text,
    PRIMARY KEY (ingredient_id)
  ) ON COMMIT DROP;
  
  -- Loop through all recipes in the grocery list
  FOR recipe_record IN 
    SELECT glr.recipe_id, glr.servings_multiplier, r.servings as original_servings
    FROM grocery_list_recipes glr
    JOIN recipes r ON glr.recipe_id = r.id
    WHERE glr.grocery_list_id = list_id
  LOOP
    -- Calculate the scaling factor
    DECLARE
      scale_factor decimal := recipe_record.servings_multiplier / recipe_record.original_servings;
    BEGIN
      -- Loop through ingredients for this recipe (including null quantities)
      FOR ingredient_record IN
        SELECT 
          ri.ingredient_id,
          CASE 
            WHEN ri.unit_amount IS NOT NULL THEN ri.unit_amount * scale_factor 
            ELSE NULL 
          END as scaled_quantity,
          ri.unit_id,
          ri.note as notes,
          u.base_conversion_factor,
          u.type as unit_type,
          ri.unit_amount IS NULL as is_null_quantity
        FROM recipe_ingredients ri
        LEFT JOIN units u ON ri.unit_id = u.id
        WHERE ri.recipe_id = recipe_record.recipe_id
      LOOP
        -- Handle ingredients with null quantities
        IF ingredient_record.is_null_quantity THEN
          INSERT INTO temp_null_quantity_ingredients (
            ingredient_id,
            unit_id,
            source_recipes,
            notes
          )
          VALUES (
            ingredient_record.ingredient_id,
            ingredient_record.unit_id,
            ARRAY[recipe_record.recipe_id],
            ingredient_record.notes
          )
          ON CONFLICT (ingredient_id) DO UPDATE
          SET 
            -- Prefer non-blank unit over blank unit
            unit_id = CASE 
              WHEN temp_null_quantity_ingredients.unit_id = 'f97badf3-daeb-4f07-84df-9bd19e7726e8'::uuid 
                   AND EXCLUDED.unit_id != 'f97badf3-daeb-4f07-84df-9bd19e7726e8'::uuid 
              THEN EXCLUDED.unit_id
              ELSE temp_null_quantity_ingredients.unit_id
            END,
            source_recipes = array_cat(temp_null_quantity_ingredients.source_recipes, EXCLUDED.source_recipes),
            notes = CASE 
              WHEN temp_null_quantity_ingredients.notes IS NULL THEN EXCLUDED.notes
              WHEN EXCLUDED.notes IS NULL THEN temp_null_quantity_ingredients.notes
              WHEN temp_null_quantity_ingredients.notes = EXCLUDED.notes THEN temp_null_quantity_ingredients.notes
              ELSE temp_null_quantity_ingredients.notes || '; ' || EXCLUDED.notes
            END;
        -- Separate handling for units without base conversion
        ELSIF ingredient_record.base_conversion_factor IS NULL THEN
          -- Insert into temp table for no-conversion units
          INSERT INTO temp_ingredient_no_conversion (
            ingredient_id, 
            unit_id,
            total_quantity, 
            unit_type, 
            source_recipes, 
            notes
          )
          VALUES (
            ingredient_record.ingredient_id,
            ingredient_record.unit_id,
            ingredient_record.scaled_quantity,
            ingredient_record.unit_type,
            ARRAY[recipe_record.recipe_id],
            ingredient_record.notes
          )
          ON CONFLICT (ingredient_id, unit_id) DO UPDATE
          SET 
            total_quantity = temp_ingredient_no_conversion.total_quantity + EXCLUDED.total_quantity,
            source_recipes = array_cat(temp_ingredient_no_conversion.source_recipes, EXCLUDED.source_recipes),
            notes = CASE 
              WHEN temp_ingredient_no_conversion.notes IS NULL THEN EXCLUDED.notes
              WHEN EXCLUDED.notes IS NULL THEN temp_ingredient_no_conversion.notes
              WHEN temp_ingredient_no_conversion.notes = EXCLUDED.notes THEN temp_ingredient_no_conversion.notes
              ELSE temp_ingredient_no_conversion.notes || '; ' || EXCLUDED.notes
            END;
        ELSE
          -- Normal processing for units with base conversion
          DECLARE
            base_quantity decimal := ingredient_record.scaled_quantity * ingredient_record.base_conversion_factor;
          BEGIN
            -- Insert or update in temp table
            INSERT INTO temp_ingredient_aggregation (
              ingredient_id, 
              total_base_quantity, 
              unit_type, 
              source_recipes, 
              notes
            )
            VALUES (
              ingredient_record.ingredient_id,
              base_quantity,
              ingredient_record.unit_type,
              ARRAY[recipe_record.recipe_id],
              ingredient_record.notes
            )
            ON CONFLICT (ingredient_id, unit_type) DO UPDATE
            SET 
              total_base_quantity = temp_ingredient_aggregation.total_base_quantity + EXCLUDED.total_base_quantity,
              source_recipes = array_cat(temp_ingredient_aggregation.source_recipes, EXCLUDED.source_recipes),
              notes = CASE 
                WHEN temp_ingredient_aggregation.notes IS NULL THEN EXCLUDED.notes
                WHEN EXCLUDED.notes IS NULL THEN temp_ingredient_aggregation.notes
                WHEN temp_ingredient_aggregation.notes = EXCLUDED.notes THEN temp_ingredient_aggregation.notes
                ELSE temp_ingredient_aggregation.notes || '; ' || EXCLUDED.notes
              END;
          END;
        END IF;
      END LOOP;
    END;
  END LOOP;
  
  -- Now convert aggregated base quantities back to appropriate display units
  -- Each ingredient+unit_type combination will become a separate grocery list item
  FOR ingredient_record IN
    SELECT * FROM temp_ingredient_aggregation
  LOOP
    -- Find the most commonly used unit for this ingredient across all recipes
    -- or use a default unit based on the quantity
    SELECT unit_id INTO preferred_unit_id
    FROM (
      -- First priority: most frequently used unit for this ingredient
      SELECT ri.unit_id, COUNT(*) as usage_count
      FROM recipe_ingredients ri
      JOIN units u ON ri.unit_id = u.id
      WHERE ri.ingredient_id = ingredient_record.ingredient_id
        AND u.type = ingredient_record.unit_type
      GROUP BY ri.unit_id
      ORDER BY usage_count DESC
      LIMIT 1
    ) preferred_units;
    
    -- If no preferred unit found, select a reasonable default based on quantity
    IF preferred_unit_id IS NULL THEN
      SELECT id INTO preferred_unit_id
      FROM units
      WHERE type = ingredient_record.unit_type
        AND system IN ('metric', 'imperial')  -- Prefer standard systems
      ORDER BY 
        CASE 
          -- For small quantities, prefer smaller units (larger conversion factor)
          WHEN ingredient_record.total_base_quantity < 100 THEN -base_conversion_factor
          -- For large quantities, prefer larger units (smaller conversion factor)
          ELSE base_conversion_factor
        END,
        display_order ASC
      LIMIT 1;
    END IF;
    
    -- Convert from base unit back to preferred unit
    SELECT 
      CASE 
        WHEN u.base_conversion_factor IS NOT NULL AND u.base_conversion_factor > 0 THEN
          ingredient_record.total_base_quantity / u.base_conversion_factor
        ELSE
          ingredient_record.total_base_quantity
      END INTO converted_quantity
    FROM units u
    WHERE u.id = preferred_unit_id;
    
    -- Insert the consolidated item
    INSERT INTO grocery_list_items (
      grocery_list_id,
      ingredient_id,
      quantity,
      unit_id,
      notes,
      is_manual,
      source_recipes
    ) VALUES (
      list_id,
      ingredient_record.ingredient_id,
      ROUND(converted_quantity, 2),  -- Round to 2 decimal places for cleaner display
      preferred_unit_id,
      ingredient_record.notes,
      false,
      ingredient_record.source_recipes
    );
  END LOOP;
  
  -- Handle ingredients with no base conversion factor
  FOR ingredient_record IN
    SELECT * FROM temp_ingredient_no_conversion
  LOOP
    -- Insert items without base conversion as separate grocery list items
    INSERT INTO grocery_list_items (
      grocery_list_id,
      ingredient_id,
      quantity,
      unit_id,
      notes,
      is_manual,
      source_recipes
    ) VALUES (
      list_id,
      ingredient_record.ingredient_id,
      ROUND(ingredient_record.total_quantity, 2),
      ingredient_record.unit_id,
      ingredient_record.notes,
      false,
      ingredient_record.source_recipes
    );
  END LOOP;
  
  -- Handle ingredients with null quantities
  FOR ingredient_record IN
    SELECT * FROM temp_null_quantity_ingredients
  LOOP
    -- Insert items with null quantities (like "to taste" ingredients)
    INSERT INTO grocery_list_items (
      grocery_list_id,
      ingredient_id,
      quantity,
      unit_id,
      notes,
      is_manual,
      source_recipes
    ) VALUES (
      list_id,
      ingredient_record.ingredient_id,
      NULL,  -- Keep quantity as NULL
      ingredient_record.unit_id,
      ingredient_record.notes,
      false,
      ingredient_record.source_recipes
    );
  END LOOP;

  -- Explicitly drop temporary tables (optional cleanup)
  DROP TABLE IF EXISTS temp_ingredient_aggregation;
  DROP TABLE IF EXISTS temp_ingredient_no_conversion;
  DROP TABLE IF EXISTS temp_null_quantity_ingredients;
  
  -- Update the grocery list timestamp
  UPDATE grocery_lists SET updated_at = now() WHERE id = list_id;
END;$function$
;

CREATE OR REPLACE FUNCTION public.remove_recipe_from_grocery_list(list_id uuid, recipe_id bigint)
 RETURNS boolean
 LANGUAGE plpgsql
AS $function$BEGIN
    -- Delete the specific recipe from the grocery list
    DELETE FROM grocery_list_recipes 
    WHERE grocery_list_id = list_id 
      AND recipe_list_recipes.recipe_id = recipe_id;
    
    -- Return true if a row was deleted, false otherwise
    RETURN FOUND;
END;$function$
;

CREATE OR REPLACE FUNCTION public.trigger_delete_old_anonymous_users()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    deleted_count INTEGER;
BEGIN
    SELECT deleted_count INTO deleted_count 
    FROM delete_old_anonymous_users();
    
    -- Optional: You can add logging or notification here
    RAISE NOTICE 'Deleted % old anonymous users', deleted_count;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.trigger_regenerate_grocery_list()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN
    PERFORM regenerate_grocery_list_items(NEW.grocery_list_id);
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    PERFORM regenerate_grocery_list_items(OLD.grocery_list_id);
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$function$
;

grant delete on table "public"."grocery_aisles" to "anon";

grant insert on table "public"."grocery_aisles" to "anon";

grant references on table "public"."grocery_aisles" to "anon";

grant select on table "public"."grocery_aisles" to "anon";

grant trigger on table "public"."grocery_aisles" to "anon";

grant truncate on table "public"."grocery_aisles" to "anon";

grant update on table "public"."grocery_aisles" to "anon";

grant delete on table "public"."grocery_aisles" to "authenticated";

grant insert on table "public"."grocery_aisles" to "authenticated";

grant references on table "public"."grocery_aisles" to "authenticated";

grant select on table "public"."grocery_aisles" to "authenticated";

grant trigger on table "public"."grocery_aisles" to "authenticated";

grant truncate on table "public"."grocery_aisles" to "authenticated";

grant update on table "public"."grocery_aisles" to "authenticated";

grant delete on table "public"."grocery_aisles" to "service_role";

grant insert on table "public"."grocery_aisles" to "service_role";

grant references on table "public"."grocery_aisles" to "service_role";

grant select on table "public"."grocery_aisles" to "service_role";

grant trigger on table "public"."grocery_aisles" to "service_role";

grant truncate on table "public"."grocery_aisles" to "service_role";

grant update on table "public"."grocery_aisles" to "service_role";

grant delete on table "public"."grocery_list_items" to "anon";

grant insert on table "public"."grocery_list_items" to "anon";

grant references on table "public"."grocery_list_items" to "anon";

grant select on table "public"."grocery_list_items" to "anon";

grant trigger on table "public"."grocery_list_items" to "anon";

grant truncate on table "public"."grocery_list_items" to "anon";

grant update on table "public"."grocery_list_items" to "anon";

grant delete on table "public"."grocery_list_items" to "authenticated";

grant insert on table "public"."grocery_list_items" to "authenticated";

grant references on table "public"."grocery_list_items" to "authenticated";

grant select on table "public"."grocery_list_items" to "authenticated";

grant trigger on table "public"."grocery_list_items" to "authenticated";

grant truncate on table "public"."grocery_list_items" to "authenticated";

grant update on table "public"."grocery_list_items" to "authenticated";

grant delete on table "public"."grocery_list_items" to "service_role";

grant insert on table "public"."grocery_list_items" to "service_role";

grant references on table "public"."grocery_list_items" to "service_role";

grant select on table "public"."grocery_list_items" to "service_role";

grant trigger on table "public"."grocery_list_items" to "service_role";

grant truncate on table "public"."grocery_list_items" to "service_role";

grant update on table "public"."grocery_list_items" to "service_role";

grant delete on table "public"."grocery_list_recipes" to "anon";

grant insert on table "public"."grocery_list_recipes" to "anon";

grant references on table "public"."grocery_list_recipes" to "anon";

grant select on table "public"."grocery_list_recipes" to "anon";

grant trigger on table "public"."grocery_list_recipes" to "anon";

grant truncate on table "public"."grocery_list_recipes" to "anon";

grant update on table "public"."grocery_list_recipes" to "anon";

grant delete on table "public"."grocery_list_recipes" to "authenticated";

grant insert on table "public"."grocery_list_recipes" to "authenticated";

grant references on table "public"."grocery_list_recipes" to "authenticated";

grant select on table "public"."grocery_list_recipes" to "authenticated";

grant trigger on table "public"."grocery_list_recipes" to "authenticated";

grant truncate on table "public"."grocery_list_recipes" to "authenticated";

grant update on table "public"."grocery_list_recipes" to "authenticated";

grant delete on table "public"."grocery_list_recipes" to "service_role";

grant insert on table "public"."grocery_list_recipes" to "service_role";

grant references on table "public"."grocery_list_recipes" to "service_role";

grant select on table "public"."grocery_list_recipes" to "service_role";

grant trigger on table "public"."grocery_list_recipes" to "service_role";

grant truncate on table "public"."grocery_list_recipes" to "service_role";

grant update on table "public"."grocery_list_recipes" to "service_role";

grant delete on table "public"."grocery_lists" to "anon";

grant insert on table "public"."grocery_lists" to "anon";

grant references on table "public"."grocery_lists" to "anon";

grant select on table "public"."grocery_lists" to "anon";

grant trigger on table "public"."grocery_lists" to "anon";

grant truncate on table "public"."grocery_lists" to "anon";

grant update on table "public"."grocery_lists" to "anon";

grant delete on table "public"."grocery_lists" to "authenticated";

grant insert on table "public"."grocery_lists" to "authenticated";

grant references on table "public"."grocery_lists" to "authenticated";

grant select on table "public"."grocery_lists" to "authenticated";

grant trigger on table "public"."grocery_lists" to "authenticated";

grant truncate on table "public"."grocery_lists" to "authenticated";

grant update on table "public"."grocery_lists" to "authenticated";

grant delete on table "public"."grocery_lists" to "service_role";

grant insert on table "public"."grocery_lists" to "service_role";

grant references on table "public"."grocery_lists" to "service_role";

grant select on table "public"."grocery_lists" to "service_role";

grant trigger on table "public"."grocery_lists" to "service_role";

grant truncate on table "public"."grocery_lists" to "service_role";

grant update on table "public"."grocery_lists" to "service_role";

grant delete on table "public"."ingredients" to "anon";

grant insert on table "public"."ingredients" to "anon";

grant references on table "public"."ingredients" to "anon";

grant select on table "public"."ingredients" to "anon";

grant trigger on table "public"."ingredients" to "anon";

grant truncate on table "public"."ingredients" to "anon";

grant update on table "public"."ingredients" to "anon";

grant delete on table "public"."ingredients" to "authenticated";

grant insert on table "public"."ingredients" to "authenticated";

grant references on table "public"."ingredients" to "authenticated";

grant select on table "public"."ingredients" to "authenticated";

grant trigger on table "public"."ingredients" to "authenticated";

grant truncate on table "public"."ingredients" to "authenticated";

grant update on table "public"."ingredients" to "authenticated";

grant delete on table "public"."ingredients" to "service_role";

grant insert on table "public"."ingredients" to "service_role";

grant references on table "public"."ingredients" to "service_role";

grant select on table "public"."ingredients" to "service_role";

grant trigger on table "public"."ingredients" to "service_role";

grant truncate on table "public"."ingredients" to "service_role";

grant update on table "public"."ingredients" to "service_role";

grant delete on table "public"."recipe_ingredients" to "anon";

grant insert on table "public"."recipe_ingredients" to "anon";

grant references on table "public"."recipe_ingredients" to "anon";

grant select on table "public"."recipe_ingredients" to "anon";

grant trigger on table "public"."recipe_ingredients" to "anon";

grant truncate on table "public"."recipe_ingredients" to "anon";

grant update on table "public"."recipe_ingredients" to "anon";

grant delete on table "public"."recipe_ingredients" to "authenticated";

grant insert on table "public"."recipe_ingredients" to "authenticated";

grant references on table "public"."recipe_ingredients" to "authenticated";

grant select on table "public"."recipe_ingredients" to "authenticated";

grant trigger on table "public"."recipe_ingredients" to "authenticated";

grant truncate on table "public"."recipe_ingredients" to "authenticated";

grant update on table "public"."recipe_ingredients" to "authenticated";

grant delete on table "public"."recipe_ingredients" to "service_role";

grant insert on table "public"."recipe_ingredients" to "service_role";

grant references on table "public"."recipe_ingredients" to "service_role";

grant select on table "public"."recipe_ingredients" to "service_role";

grant trigger on table "public"."recipe_ingredients" to "service_role";

grant truncate on table "public"."recipe_ingredients" to "service_role";

grant update on table "public"."recipe_ingredients" to "service_role";

grant delete on table "public"."recipes" to "anon";

grant insert on table "public"."recipes" to "anon";

grant references on table "public"."recipes" to "anon";

grant select on table "public"."recipes" to "anon";

grant trigger on table "public"."recipes" to "anon";

grant truncate on table "public"."recipes" to "anon";

grant update on table "public"."recipes" to "anon";

grant delete on table "public"."recipes" to "authenticated";

grant insert on table "public"."recipes" to "authenticated";

grant references on table "public"."recipes" to "authenticated";

grant select on table "public"."recipes" to "authenticated";

grant trigger on table "public"."recipes" to "authenticated";

grant truncate on table "public"."recipes" to "authenticated";

grant update on table "public"."recipes" to "authenticated";

grant delete on table "public"."recipes" to "service_role";

grant insert on table "public"."recipes" to "service_role";

grant references on table "public"."recipes" to "service_role";

grant select on table "public"."recipes" to "service_role";

grant trigger on table "public"."recipes" to "service_role";

grant truncate on table "public"."recipes" to "service_role";

grant update on table "public"."recipes" to "service_role";

grant delete on table "public"."subaisle_positions" to "anon";

grant insert on table "public"."subaisle_positions" to "anon";

grant references on table "public"."subaisle_positions" to "anon";

grant select on table "public"."subaisle_positions" to "anon";

grant trigger on table "public"."subaisle_positions" to "anon";

grant truncate on table "public"."subaisle_positions" to "anon";

grant update on table "public"."subaisle_positions" to "anon";

grant delete on table "public"."subaisle_positions" to "authenticated";

grant insert on table "public"."subaisle_positions" to "authenticated";

grant references on table "public"."subaisle_positions" to "authenticated";

grant select on table "public"."subaisle_positions" to "authenticated";

grant trigger on table "public"."subaisle_positions" to "authenticated";

grant truncate on table "public"."subaisle_positions" to "authenticated";

grant update on table "public"."subaisle_positions" to "authenticated";

grant delete on table "public"."subaisle_positions" to "service_role";

grant insert on table "public"."subaisle_positions" to "service_role";

grant references on table "public"."subaisle_positions" to "service_role";

grant select on table "public"."subaisle_positions" to "service_role";

grant trigger on table "public"."subaisle_positions" to "service_role";

grant truncate on table "public"."subaisle_positions" to "service_role";

grant update on table "public"."subaisle_positions" to "service_role";

grant delete on table "public"."units" to "anon";

grant insert on table "public"."units" to "anon";

grant references on table "public"."units" to "anon";

grant select on table "public"."units" to "anon";

grant trigger on table "public"."units" to "anon";

grant truncate on table "public"."units" to "anon";

grant update on table "public"."units" to "anon";

grant delete on table "public"."units" to "authenticated";

grant insert on table "public"."units" to "authenticated";

grant references on table "public"."units" to "authenticated";

grant select on table "public"."units" to "authenticated";

grant trigger on table "public"."units" to "authenticated";

grant truncate on table "public"."units" to "authenticated";

grant update on table "public"."units" to "authenticated";

grant delete on table "public"."units" to "service_role";

grant insert on table "public"."units" to "service_role";

grant references on table "public"."units" to "service_role";

grant select on table "public"."units" to "service_role";

grant trigger on table "public"."units" to "service_role";

grant truncate on table "public"."units" to "service_role";

grant update on table "public"."units" to "service_role";

grant delete on table "public"."units_backup_before_fix" to "anon";

grant insert on table "public"."units_backup_before_fix" to "anon";

grant references on table "public"."units_backup_before_fix" to "anon";

grant select on table "public"."units_backup_before_fix" to "anon";

grant trigger on table "public"."units_backup_before_fix" to "anon";

grant truncate on table "public"."units_backup_before_fix" to "anon";

grant update on table "public"."units_backup_before_fix" to "anon";

grant delete on table "public"."units_backup_before_fix" to "authenticated";

grant insert on table "public"."units_backup_before_fix" to "authenticated";

grant references on table "public"."units_backup_before_fix" to "authenticated";

grant select on table "public"."units_backup_before_fix" to "authenticated";

grant trigger on table "public"."units_backup_before_fix" to "authenticated";

grant truncate on table "public"."units_backup_before_fix" to "authenticated";

grant update on table "public"."units_backup_before_fix" to "authenticated";

grant delete on table "public"."units_backup_before_fix" to "service_role";

grant insert on table "public"."units_backup_before_fix" to "service_role";

grant references on table "public"."units_backup_before_fix" to "service_role";

grant select on table "public"."units_backup_before_fix" to "service_role";

grant trigger on table "public"."units_backup_before_fix" to "service_role";

grant truncate on table "public"."units_backup_before_fix" to "service_role";

grant update on table "public"."units_backup_before_fix" to "service_role";


  create policy "Enable read access for all users"
  on "public"."grocery_aisles"
  as permissive
  for select
  to public
using (true);



  create policy "Users can manage own grocery list items"
  on "public"."grocery_list_items"
  as permissive
  for all
  to public
using ((EXISTS ( SELECT 1
   FROM public.grocery_lists gl
  WHERE ((gl.id = grocery_list_items.grocery_list_id) AND (gl.user_id = auth.uid())))));



  create policy "Users can manage own grocery list recipes"
  on "public"."grocery_list_recipes"
  as permissive
  for all
  to public
using ((EXISTS ( SELECT 1
   FROM public.grocery_lists gl
  WHERE ((gl.id = grocery_list_recipes.grocery_list_id) AND (gl.user_id = auth.uid())))));



  create policy "Users can manage own grocery lists"
  on "public"."grocery_lists"
  as permissive
  for all
  to public
using ((auth.uid() = user_id));



  create policy "Enable insert for authenticated users only"
  on "public"."ingredients"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."ingredients"
  as permissive
  for select
  to public
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."recipe_ingredients"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."recipe_ingredients"
  as permissive
  for select
  to public
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."recipes"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."recipes"
  as permissive
  for select
  to public
using (true);



  create policy "Enable users to view their own data only"
  on "public"."recipes"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = created_by));



  create policy "Enable read access for all users"
  on "public"."subaisle_positions"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."units"
  as permissive
  for select
  to public
using (true);


CREATE TRIGGER grocery_list_recipes_change_trigger AFTER INSERT OR DELETE OR UPDATE ON public.grocery_list_recipes FOR EACH ROW EXECUTE FUNCTION public.trigger_regenerate_grocery_list();

CREATE TRIGGER on_anonymous_user_create BEFORE INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_anonymous_user();


  create policy "Allow INSERT for authenticated users only"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (true);



